import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://rahulshettyacademy.com/client/#/auth/login');
  await page.getByRole('textbox', { name: 'email@example.com' }).click();
  await page.getByRole('textbox', { name: 'email@example.com' }).fill('anshika@gmail.com');
  await page.getByRole('textbox', { name: 'email@example.com' }).press('Tab');
  await page.getByRole('textbox', { name: 'enter your passsword' }).fill('Iamking@000');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'View' }).first().click();
  await page.getByRole('heading', { name: 'ADIDAS ORIGINAL' }).click();
  await page.getByRole('button', { name: 'Add to Cart' }).click();
  await page.getByRole('button', { name: '   Cart' }).click();
  await page.getByRole('button', { name: ' HOME' }).click();
  await page.getByRole('button', { name: ' Add To Cart' }).nth(1).click();
  await page.getByRole('button', { name: '   Cart' }).click();
  await page.getByRole('button', { name: '   ORDERS' }).click();
  await page.getByRole('button', { name: ' HOME' }).click();
  await page.getByRole('button', { name: 'View' }).nth(2).click();
  await page.getByRole('button', { name: 'Add to Cart' }).click();
  await page.getByRole('link', { name: 'Continue Shopping❯' }).click();
  await page.getByRole('button', { name: '   Cart' }).click();
  await page.getByRole('button', { name: 'Checkout❯' }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('combobox').first().selectOption('05');
  await page.getByRole('combobox').nth(1).selectOption('26');
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).fill('123');
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('RakeshKumar');
  await page.getByRole('textbox').nth(2).press('Tab');
  await page.locator('input[name="coupon"]').fill('rahulshettyacademy');
  await page.getByRole('button', { name: 'Apply Coupon' }).click();
  await page.getByText('* Coupon Applied').click();
  await page.getByRole('textbox', { name: 'Select Country' }).click();
  await page.getByRole('textbox', { name: 'Select Country' }).fill('ind');
  await page.getByRole('button', { name: ' India' }).click();
  await page.getByText('Place Order').click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Click To Download Order' }).click();
  const download = await downloadPromise;
  await page.getByText('Orders History Page').click();
  await page.getByRole('cell', { name: 'Thu Aug' }).nth(2).click();
  await page.getByRole('cell', { name: 'Thu Aug' }).nth(1).click();
  await page.getByRole('button', { name: 'View' }).nth(2).click();
  await page.getByText('View Orders').click();
  await page.getByRole('button', { name: 'View' }).nth(1).click();
  await page.getByText('View Orders').click();
  await page.getByRole('button', { name: 'View' }).first().click();
  await page.getByText('View Orders').click();
  await page.getByRole('button', { name: 'Delete' }).nth(1).click();
  await page.getByRole('button', { name: ' HOME' }).click();
  await page.getByRole('button', { name: 'Sign Out' }).click();
});